# Generated by Django 5.0.6 on 2025-02-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_alter_photo_image'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='customers', to='media.photo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='partners', to='media.photo'),
        ),
        migrations.AddField(
            model_name='user',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='users', to='media.photo'),
        ),
    ]
