# Generated by Django 5.0.6 on 2026-03-14 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customer_photos_partner_photos_user_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=500)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='users.customer')),
            ],
            options={
                'unique_together': {('customer', 'key')},
            },
        ),
    ]
