# Generated by Django 5.0.6 on 2024-05-28 16:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('planting_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('harvest_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.plant')),
            ],
        ),
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('date_received', models.DateField()),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxon.variety')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='seed_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('event_date', models.DateField()),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.plant')),
                ('seed_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot')),
            ],
        ),
    ]
