# Generated by Django 5.0.6 on 2024-06-30 18:32

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('collection', 'Collection'), ('fermentation_start', 'Fermentation Start'), ('fermentation_end', 'Fermentation End'), ('storage', 'Storage'), ('planting', 'Planting'), ('germination', 'Germination'), ('first_true_leaves', 'First True Leaves'), ('transplant', 'Transplant'), ('watering', 'Watering'), ('fertilizing', 'Fertilizing'), ('pruning', 'Pruning'), ('treatment', 'Treatment'), ('packaging', 'Packaging'), ('sale', 'Sale')], default='collection', max_length=50)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Harvest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Planting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('growing', 'Growing'), ('harvested', 'Harvested'), ('failed', 'Failed')], default='growing', max_length=50)),
                ('source_object_id', models.UUIDField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedlingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units', models.CharField(default='seeds', max_length=50)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('germinating', 'Germinating'), ('transplanted', 'Transplanted'), ('failed', 'Failed')], default=('germinating', 'Germinating'), max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SeedLot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='New Seedlot', max_length=100)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units', models.CharField(blank=True, max_length=50, null=True)),
                ('date_received', models.DateField(blank=True, default=datetime.datetime.now, null=True)),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
