# Generated by Django 5.0.6 on 2024-06-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0001_initial'),
        ('media', '0002_initial'),
        ('taxon', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='event',
            name='related_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.event'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='harvests', to='media.photo'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='source_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_harvests', to='users.partner'),
        ),
        migrations.AddField(
            model_name='planting',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='planting',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='plants', to='media.photo'),
        ),
        migrations.AddField(
            model_name='planting',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'farm'), ('model__in', ['seedlot', 'seedlingbatch', 'planting'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='planting',
            name='source_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_plants', to='users.partner'),
        ),
        migrations.AddField(
            model_name='planting',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plants',
            field=models.ManyToManyField(related_name='harvests', to='farm.planting'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='farm.seedlingbatch'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seedlingBatches', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seed_lots', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.harvest'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='source_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_seedlots', to='users.partner'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_lots', to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='seed_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_batches', to='farm.seedlot'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.seedlot'),
        ),
    ]
