# Generated by Django 5.0.6 on 2024-06-08 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('taxon', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='plant',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='plant',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='harvest',
            name='plants',
            field=models.ManyToManyField(related_name='harvests', to='farm.plant'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='parent_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_batches', to='farm.seedlingbatch'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='plant',
            name='seedling_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='farm.seedlingbatch'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.organization'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.harvest'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_lots', to='taxon.variety'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='seed_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seedling_batches', to='farm.seedlot'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.seedlot'),
        ),
        migrations.AddField(
            model_name='plant',
            name='seed_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='farm.seedlot'),
        ),
        migrations.AddField(
            model_name='plant',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.seedlot'),
        ),
    ]
