# Generated by Django 5.0.6 on 2024-05-28 17:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='harvest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.harvest'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='seed_lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot'),
        ),
        migrations.CreateModel(
            name='SeedlingBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('sowing_date', models.DateField()),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='seedling_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.seedlingbatch'),
        ),
        migrations.AddField(
            model_name='plant',
            name='seedling_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='farm.seedlingbatch'),
        ),
    ]
