# Generated by Django 5.0.6 on 2024-06-01 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedlot',
            name='date_received',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
