# Generated by Django 5.0.6 on 2024-05-30 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_harvest_photos_plant_photos_seedlingbatch_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedlingbatch',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedlingbatch',
            name='sowing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedlot',
            name='date_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seedlot',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
