# Generated by Django 5.0.6 on 2024-06-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0002_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='harvests', to='media.photo'),
        ),
        migrations.AddField(
            model_name='plant',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='plants', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seedlingBatches', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seed_lots', to='media.photo'),
        ),
    ]
