# Generated by Django 5.0.6 on 2024-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0003_alter_seedlingbatch_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seedlingbatch',
            options={'verbose_name_plural': 'Seedling Batches'},
        ),
    ]
