# Generated by Django 5.0.6 on 2024-05-31 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_alter_seedlingbatch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='seedlot',
            name='origin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
