# Generated by Django 5.0.6 on 2024-07-02 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0004_remove_event_related_item_event_content_type_and_more'),
        ('taxon', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='harvest',
            name='variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='taxon.variety'),
        ),
    ]
