# Generated by Django 5.0.6 on 2025-07-17 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0005_harvest_variety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seedlot',
            old_name='origin',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='seedlot',
            name='source',
        ),
        migrations.AddField(
            model_name='seedlot',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'farm'), ('model__in', ['harvest', 'planting', 'seedlot'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='source_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
