# Generated by Django 5.0.6 on 2024-05-31 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0005_seedlot_origin'),
        ('taxon', '0009_alter_taxon_options_alter_variety_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seedlot',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seed_lots', to='taxon.variety'),
        ),
    ]
