# Generated by Django 5.0.6 on 2025-07-18 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('farm', '0006_rename_origin_seedlot_vendor_remove_seedlot_source_and_more'),
        ('media', '0003_alter_photo_image'),
        ('users', '0002_customer_photos_partner_photos_user_photos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seedlingbatch',
            name='seed_lot',
        ),
        migrations.RemoveField(
            model_name='seedlingbatch',
            name='source',
        ),
        migrations.RemoveField(
            model_name='seedlingbatch',
            name='status',
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='source_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('app_label', 'farm'), ('model__in', ['seedlot', 'planting', 'seedlingbatch'])), null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='source_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='source_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourced_seedling_batches', to='users.partner'),
        ),
        migrations.AddField(
            model_name='seedlingbatch',
            name='vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seedlingbatch',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seedling_batches', to='media.photo'),
        ),
    ]
