# Generated by Django 5.0.6 on 2026-03-14 23:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0007_remove_seedlingbatch_seed_lot_and_more'),
        ('users', '0003_customersetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_performed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='harvest',
            name='status',
            field=models.CharField(choices=[('placeholder', 'Placeholder'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='in_progress', max_length=20),
        ),
        migrations.AddField(
            model_name='seedlot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seed_lots', to='farm.location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='harvest',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='planting',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plantings', to='farm.location'),
        ),
        migrations.AlterField(
            model_name='seedlingbatch',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seedling_batches', to='farm.location'),
        ),
        migrations.CreateModel(
            name='HarvestContainer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('container_type', models.CharField(choices=[('bag', 'Bag'), ('basket', 'Basket'), ('bin', 'Bin'), ('jug', 'Jug'), ('tray', 'Tray'), ('other', 'Other')], default='other', max_length=50)),
                ('status', models.CharField(choices=[('available', 'Available'), ('in_use', 'In Use'), ('dispatched', 'Dispatched')], default='available', max_length=20)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stored_containers', to='farm.location')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='harvest',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='farm.harvestcontainer'),
        ),
    ]
