# Generated by Django 5.0.6 on 2024-06-01 17:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_packaged', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('plants', models.ManyToManyField(related_name='packages', to='farm.plant')),
                ('seedling_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.seedlingbatch')),
            ],
        ),
        migrations.CreateModel(
            name='ProducePackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_units', models.CharField(default='kg', max_length=50)),
                ('date_packaged', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('harvest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.harvest')),
            ],
        ),
        migrations.CreateModel(
            name='SeedPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity_units', models.CharField(default='seeds', max_length=50)),
                ('date_packaged', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('seed_lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot')),
            ],
        ),
    ]
