# Generated by Django 5.0.6 on 2024-06-30 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farm', '0001_initial'),
        ('media', '0002_initial'),
        ('shop', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantpackage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='plantpackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='PlantPackages', to='media.photo'),
        ),
        migrations.AddField(
            model_name='plantpackage',
            name='plants',
            field=models.ManyToManyField(related_name='packages', to='farm.planting'),
        ),
        migrations.AddField(
            model_name='plantpackage',
            name='seedling_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='farm.seedlingbatch'),
        ),
        migrations.AddField(
            model_name='producepackage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='producepackage',
            name='harvest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.harvest'),
        ),
        migrations.AddField(
            model_name='producepackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='produce_packages', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedpackage',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AddField(
            model_name='seedpackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seed_packages', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedpackage',
            name='seed_lot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farm.seedlot'),
        ),
    ]
