# Generated by Django 5.0.6 on 2024-06-09 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_photo_content_type_photo_object_id'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantpackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='PlantPackages', to='media.photo'),
        ),
        migrations.AddField(
            model_name='producepackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='produce_packages', to='media.photo'),
        ),
        migrations.AddField(
            model_name='seedpackage',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='seed_packages', to='media.photo'),
        ),
    ]
