# Generated by Django 5.0.6 on 2024-07-02 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plantpackage',
            options={'verbose_name': 'plantpackage', 'verbose_name_plural': 'plantpackages'},
        ),
        migrations.AlterModelOptions(
            name='producepackage',
            options={'verbose_name': 'producepackage', 'verbose_name_plural': 'producepackages'},
        ),
        migrations.AlterModelOptions(
            name='seedpackage',
            options={'verbose_name': 'seedpackage', 'verbose_name_plural': 'seedpackages'},
        ),
    ]
