# Generated by Django 5.0.6 on 2025-02-20 02:01

import media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to=media.models.customer_photo_path),
        ),
    ]
