# Generated by Django 5.0.6 on 2024-06-08 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('species_name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('herb', 'Herb'), ('flower', 'Flower'), ('grass', 'Grass'), ('shrub', 'Shrub'), ('tree', 'Tree'), ('succulent', 'Succulent'), ('annual', 'Annual'), ('perennial', 'Perennial'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, related_name='taxons', to='media.photo')),
            ],
            options={
                'verbose_name_plural': 'Taxa',
            },
        ),
        migrations.CreateModel(
            name='Synonym',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='synonyms', to='taxon.taxon')),
            ],
        ),
        migrations.CreateModel(
            name='Variety',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('photos', models.ManyToManyField(blank=True, related_name='varieties', to='media.photo')),
                ('taxon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='taxon.taxon')),
            ],
            options={
                'verbose_name_plural': 'Varieties',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('varieties', models.ManyToManyField(related_name='characteristics', to='taxon.variety')),
            ],
        ),
    ]
