# Generated by Django 5.0.6 on 2024-06-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxon',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='taxons', to='media.photo'),
        ),
        migrations.AddField(
            model_name='variety',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='varieties', to='media.photo'),
        ),
    ]
