# Generated by Django 5.0.6 on 2024-05-28 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('species', models.ManyToManyField(related_name='common_names', to='taxon.species')),
            ],
        ),
        migrations.AddField(
            model_name='variety',
            name='common_names',
            field=models.ManyToManyField(related_name='varieties', to='taxon.commonname'),
        ),
    ]
