# Generated by Django 5.0.6 on 2024-05-29 01:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='photos/')),
                ('item_type', models.CharField(max_length=50)),
                ('item_id', models.UUIDField()),
            ],
        ),
        migrations.AddField(
            model_name='taxon',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='taxons', to='taxon.photo'),
        ),
        migrations.AddField(
            model_name='variety',
            name='photos',
            field=models.ManyToManyField(blank=True, related_name='varieties', to='taxon.photo'),
        ),
    ]
