# Generated by Django 5.0.6 on 2024-05-29 22:03

import django.db.models.deletion
from django.db import migrations, models


def set_default_taxon(apps, schema_editor):
    Variety = apps.get_model('taxon', 'Variety')
    Taxon = apps.get_model('taxon', 'Taxon')
    default_taxon = Taxon.objects.create(name='Default Taxon', type='Other')
    Variety.objects.update(taxon=default_taxon)


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0002_photo_taxon_photos_variety_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='taxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varieties',
                                    to='taxon.Taxon'),
        ),
        migrations.RunPython(set_default_taxon),
        migrations.AlterField(
            model_name='variety',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='varieties',
                                    to='taxon.Taxon'),
        ),
    ]