# Generated by Django 5.0.6 on 2024-07-07 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Synonym',
        ),
    ]
