# Generated by Django 5.0.6 on 2024-07-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_delete_synonym'),
    ]

    operations = [
        migrations.AddField(
            model_name='characteristic',
            name='taxa',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='taxon.taxon'),
        ),
        migrations.AlterField(
            model_name='characteristic',
            name='varieties',
            field=models.ManyToManyField(blank=True, related_name='characteristics', to='taxon.variety'),
        ),
    ]
