# Generated by Django 5.0.6 on 2024-05-29 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0003_variety_taxon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='taxon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='varieties', to='taxon.taxon'),
        ),
    ]
