# Generated by Django 5.0.6 on 2024-07-08 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0004_characteristic_taxa_alter_characteristic_varieties'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='characteristic',
            name='taxa',
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='value',
        ),
        migrations.RemoveField(
            model_name='characteristic',
            name='varieties',
        ),
        migrations.CreateModel(
            name='CharacteristicValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
                ('characteristic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taxon.characteristic')),
                ('taxon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxon.taxon')),
                ('variety', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='taxon.variety')),
            ],
            options={
                'unique_together': {('characteristic', 'taxon'), ('characteristic', 'variety')},
            },
        ),
        migrations.AddField(
            model_name='taxon',
            name='characteristics',
            field=models.ManyToManyField(through='taxon.CharacteristicValue', to='taxon.characteristic'),
        ),
        migrations.AddField(
            model_name='variety',
            name='characteristics',
            field=models.ManyToManyField(through='taxon.CharacteristicValue', to='taxon.characteristic'),
        ),
    ]
