# Generated by Django 5.0.6 on 2024-05-29 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0004_alter_variety_taxon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='taxon',
        ),
    ]
