# Generated by Django 5.0.6 on 2024-07-08 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0005_remove_characteristic_taxa_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characteristic',
            unique_together={('name', 'customer')},
        ),
    ]
