# Generated by Django 5.0.6 on 2024-05-30 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0006_variety_taxon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('variety', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='taxon.variety')),
            ],
        ),
    ]
