# Generated by Django 5.0.6 on 2024-05-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0008_alter_taxon_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxon',
            options={'verbose_name_plural': 'Taxa'},
        ),
        migrations.AlterModelOptions(
            name='variety',
            options={'verbose_name_plural': 'Varieties'},
        ),
    ]
