# Generated by Django 5.0.6 on 2024-05-31 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxon', '0009_alter_taxon_options_alter_variety_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='origin',
        ),
    ]
